#!/usr/bin/env python3
# Copyright (C) 2013 Karl R. Wurst
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA

####################################################################
# Creates users for GitLab from a class list generated by Blackboard
#
# From within Blackboard, go to Grade Center:Full Grade Center
# From Work Offline, choose Download
# Choose Comma delimiter, and click Submit
# Download the file.
#
# Call as:
# python create-gitlab-users.py filename
#
# where filename is the path/name of the CSV file
#
# Requires pyapi-gitlab https://github.com/Itxaka/pyapi-gitlab
# Reads your private GitLab API token from the file gitlabtoken.txt

import argparse
import csv
import sys
import gitlab   # Requires pyapi-gitlab https://github.com/Itxaka/pyapi-gitlab

GITLAB_URL = 'https://git.cs.worcester.edu'
EMAIL_DOMAIN = '@worcester.edu'

# Set up to parse arguments
parser = argparse.ArgumentParser()
parser.add_argument('filename', help='Blackboard CSV filename with user information')
parser.add_argument('-v', '--verbose', help='increase output verbosity', action='store_true')
args = parser.parse_args()

# Get my private GitLab token
# stored in a file so that I can .gitignore the file
token = open('gitlabtoken.txt').readline().strip()

# Create a GitLab object
# For our server, verify_ssl has to be False, since we have a self-signed certificate
git = gitlab.Gitlab(GITLAB_URL, token, verify_ssl=False)

# Needs utf-8 to handle the strange character Bb puts at the beginning of the file
f = open(args.filename, encoding='utf-8')
f.readline() # throw away header line

c = csv.reader(f)
# CSV file stores user information as follows:
# last name, first name, username, other stuff I ignore...

for row in c:

    name = row[1] + ' ' + row[0]        # rebuild full name
    username = row[2]
    # Password doesn't matter because GitLab will not include it in notification email,
    # but will require you to set it anyway...
    # I am just telling students to use the "Forgot password" link when they get the email.
    # If this is ever fixed, I'll have to generate a random password...
    password = 'A123456789'
    email = row[2] + EMAIL_DOMAIN       # create email address
    
    #success = git.createuser(name, username, password, email)

    if args.verbose:
        sys.stderr.write(name+', '+username+', '+email+'\n')
